# This is a basic workflow to help you get started with Actions

name: README

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - "main"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout curr repository
        uses: actions/checkout@v4

      - name: Get Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Runs a set of commands using the runners shell
      - name: Run python script
        env:
          TOKEN: ${{ secrets.TESTE }}
        run: python main.py

      - name: Update
        run: |-
          git add .
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "getuliobr/Github-Actions"
          git commit -m "Generating new SVG"
          git push
